
language: node_js
node_js:
- "node"
cache: npm
script: npm run deploy
- npm test
- npm run deploy
after_script: npm run alias
env:
  global:
    secure: W6HVaodeUs6M8ACJJPWiBNqVEjf3lO6p7D5dKjkQcq9MjHxmqIvPwVckeX0igtYhYxjc+18WY56P6njNW9BQ0nC35uD102j4h6Cp5vRKoFkq+BKOW+FQ92ouAdoKK2xnlmaJIF+NCw65gchq2lCiAYfl73OtvkvaUwVKoDW6kjWXXnocHyCuHfahgUEJAphn1hi8u54nLHXliA2rlgdGt9Z/j0lOsrS1oagqdYybYd8PEyWCV/H7kNQdyw8hr3jNBS0uEVZ9lo5emS8fLkZ34Eh9sBjXNqgbCJT+WF4Ozj9gehwAvYTLnEQ0HZmc7aYf592LaQBKa9kKk+gcEscEJvf0AwX5Q23X3fYblOkjawCF+xJdcCe6gtlnAEUuwa5YRnVbseDlbwxSSZLfUYwzgvkCUvzquL5QBxyjxUuY+SsMPMH6S4zYo09TtJMVabpziZPFxEkyq5YIe832jwumaaPUvIgYz7XpZuPkRYx3jIxHcL53gnelIKTlhfYq12+xxWUVpYsYQZx4DOa+5oebTXZoI587LCP5mVe55pqsLazp47GUlrtfBY6OzMlJksT6039r6o0z83LGOuZZMiEYONF8uHtl6EjSHxw53ULTad1chHNnDx+m327gx7bz1tR5LFA93BuOHn6I+ZvjuOST66mqGJnUcvs+tC25zKKXXKo=
